<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:

1. Data latih/training adalah data yang akan dipelajari oleh suatu model. Data validasi adalah data yang digunakan untuk proses validasi model dan mencegah overfitting. Data test adalah data yang digunakan untuk menguji model.

2. Cara menilai suatu model adalah dengan melihat seberapa besar akurasi yang diperoleh dari prediksi sebuah data. Data yang digunakan tidak boleh data training, tetapi data test yang diperoleh dengan membuat data baru atau dengan membagi data menggunakan train test split dari library sklearn. Menilai performa model juga dapat dilakukan dengan menggunakan cross validation yaitu membagi data menjadi sebanyak K bagian kemudian dilakukan iterasi menghitung akurasi sebanyak K kali , lalu dirata-rata. Cara ini merupakan cara yang lebih baik daripada menguji akurasi menggunakan data test.

3. Confusion matrix adalah metode penilaian performa model yang lebih tepat dari matriks akurasi. Metode ini membagi data (y_true dan y_pred) ke dalam empat bagian, yaitu True Positive(TP), True Negative(TN), False Positive(FP), dan False Negative(FN). Berikut penjelasan keempat komponen tersebut:

  1. True Positive adalah data positif yang diprediksi positif/benar.
  2. True Negative adalah data negatif yang diprediksi negatif/benar.
  3. False Positive adalah data negatif yang diprediksi salah/positif.
  4. False Negative adalah data positif yang diprediksi salah/negatif.

  Confusion matriks sangat cocok diaplikasikan pada data dengan kondisi   jumlah data yang tidak seimbang, misalnya jumlah data penderita kanker sebanyak 10 orang sedangkan yang tidak menderita kanker sebanyak 990 orang. Tentu jika kita hanya menggunakan matriks akurasi 10 orang yang menderita kanker akan terabaikan.

4. Classification report adalah penjabaran dari confusion matrix yang meliputi precision, recall, dan f1score. Ketiga rumus tersebut menggunakan empat komponen confusion matrix yang disebutkan di atas.
  1. precision = TP/(TP + FP)
  2. recall = TP/(TP + FN)
  3. f1score = 2 * precision * recall/(precision + recall)

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [20]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [21]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [22]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [23]:
# Code here
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale

x = df.drop('survival_status', axis=1)
xs = scale(x)
y = df['survival_status']

x_train, x_test, y_train, y_test = train_test_split(xs, y, test_size=0.25, stratify=y, random_state=21)

In [24]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5, weights='distance')
model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='distance')

In [29]:
from sklearn.model_selection import cross_val_score
val_score = cross_val_score(model ,xs, y, scoring='roc_auc', cv=10)
val_score

array([0.69021739, 0.61141304, 0.36413043, 0.67934783, 0.69565217,
       0.72727273, 0.84375   , 0.64488636, 0.59375   , 0.64204545])

In [30]:
val_score.mean()

0.6492465415019764

In [31]:
y_predict = model.predict(x_test)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predict, labels=[1,2])

array([[43, 14],
       [12,  8]])

In [32]:
#classification report
from sklearn.metrics import classification_report
class_report = classification_report(y_test, y_predict, labels=[2,1])
print(class_report)

              precision    recall  f1-score   support

           2       0.36      0.40      0.38        20
           1       0.78      0.75      0.77        57

    accuracy                           0.66        77
   macro avg       0.57      0.58      0.57        77
weighted avg       0.67      0.66      0.67        77



7. Menurut saya model saya kurang baik dalam memprediksi seorang pasien mempunyai status positive meninggal kurang dari 5 tahun, karena nilainya dibawah 0.5

8. Menurut saya model saya sangat baik dalam memprediksi seorang pasien mempunyai status negatif meninggal kurang dari 5 tahun, karena nilainya lebih dari 0.5


---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:

1. Bias adalah error yang disebabkan karena model terlalu  sederhana sehingga menimbulkan error yang tinggi terhadap data training maupun data validasi. Variance adalah error yang disebabkan karena model terlalu kompleks. Variance menimbulkan error yang kecil pada data training, namun pada data validasi errornya akan sangat besar.

2. Overfitting adalah suatu kondisi dimana model terlalu banyak belajar dengan detail dan menangkap banyak noise sehingga kemampuan generalisasinya rendah dan jelek. Biasanya akurasi data training pada kondisi overfitting sangat besar namun rendah pada saat validasi. Underfitting adalah kondisi dimana model kurang banyak belajar. Pada kondisi underfitting akurasi akan rendah pada saat training maupun validasi.

3. Yang dapat kita lakukan untuk mengatur kompleksitas model yaitu dengan melakukan tunning terhadap hyperparameter

4. Model yang baik adalah yang memiliki score baik pada training maupun validating.

5. GridSearchCV akan mencoba seluruh kombinasi tiap hyperparameter yang diinginkan sedangkan RandomizedSearchCV akan memilih secara random sebanyak n-iterasi pada kombinasi hyperparameter. GridSearchCV digunakan ketika kita menginginkan hyperparameter yang lebih tepat, namun lebih lama. Sedangkan RandomizedSearchCV digunakan ketika kita menginginkan hyperparameter dengan lebih cepat.

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [33]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [34]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [35]:
#Code here
#Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale

x = df.drop('survival_status', axis=1)
xs = scale(x)
y = df['survival_status']

x_train, x_test, y_train, y_test = train_test_split(xs, y, test_size=0.25, stratify=y, random_state=21)

In [36]:
#Gunakan algoritma KNN sebagai model classifier.
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

param = {'n_neighbors':np.arange(2,80), 'weights':['uniform', 'distance']}
model = KNeighborsClassifier()

#Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection
gscv = GridSearchCV(model,param_grid=param, scoring='roc_auc', cv=5)
gscv.fit(xs, y)

GridSearchCV(cv=5, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=0)

In [37]:
#Kombinasi hyperparameter terbaik menurut saya
gscv.best_params_

{'n_neighbors': 27, 'weights': 'uniform'}

In [38]:
#Score validasi terbaik
gscv.best_score_

0.6894607843137256

In [39]:
#Melatih data training
model = KNeighborsClassifier(n_neighbors=27, weights='uniform')
model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=27, p=2,
                     weights='uniform')

In [40]:
model.classes_
#1. meninggal lebih dari 5 tahun
#2. meninggal kurang dari 5 tahun

array([1, 2])

In [41]:
model.predict_proba(x_test)[:,1]

array([0.18518519, 0.37037037, 0.33333333, 0.40740741, 0.25925926,
       0.25925926, 0.22222222, 0.22222222, 0.14814815, 0.25925926,
       0.66666667, 0.18518519, 0.18518519, 0.14814815, 0.22222222,
       0.22222222, 0.18518519, 0.18518519, 0.14814815, 0.48148148,
       0.18518519, 0.22222222, 0.22222222, 0.62962963, 0.14814815,
       0.22222222, 0.14814815, 0.18518519, 0.18518519, 0.07407407,
       0.14814815, 0.59259259, 0.18518519, 0.33333333, 0.59259259,
       0.14814815, 0.22222222, 0.18518519, 0.18518519, 0.22222222,
       0.48148148, 0.18518519, 0.14814815, 0.51851852, 0.11111111,
       0.22222222, 0.14814815, 0.11111111, 0.22222222, 0.59259259,
       0.22222222, 0.62962963, 0.14814815, 0.18518519, 0.22222222,
       0.14814815, 0.11111111, 0.51851852, 0.11111111, 0.66666667,
       0.51851852, 0.2962963 , 0.2962963 , 0.18518519, 0.22222222,
       0.11111111, 0.22222222, 0.25925926, 0.33333333, 0.14814815,
       0.25925926, 0.11111111, 0.11111111, 0.55555556, 0.22222

In [42]:
#roc auc score untuk data testing
from sklearn.metrics import roc_auc_score
y_predict = model.predict(x_test)
rac = roc_auc_score(y_test, y_predict)
rac

0.5973684210526317

Model saya termasuk baik karena nilai roc_auc_score dan validation score nya diatas 0.5



---



# Decision Tree Classifier

In [47]:
#Gunakan algoritma DTC sebagai model classifier.
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

param = {'max_depth':np.arange(2,20), 'splitter':['best', 'random']}        
model_tree = DecisionTreeClassifier()

#Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection
gscv = GridSearchCV(model_tree,param_grid=param, scoring='roc_auc', cv=5)
gscv.fit(xs, y)

GridSearchCV(cv=5, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'max_depth': array([ 2,  3,  4,  5,  6,  7,  8,  9, 1

In [50]:
gscv.best_params_

{'max_depth': 3, 'splitter': 'random'}

In [54]:
gscv.best_score_

0.693235294117647

In [55]:
#Melatih data training
model_tree = DecisionTreeClassifier(max_depth=3, splitter='random')
model_tree.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='random')

In [56]:
model_tree.predict_proba(x_test)[:,1]

array([0.21105528, 1.        , 0.21105528, 1.        , 0.21105528,
       0.21105528, 0.21105528, 0.21105528, 0.21105528, 0.21105528,
       0.75      , 0.21105528, 0.21105528, 0.21105528, 0.21105528,
       0.21105528, 0.21105528, 0.21105528, 0.21105528, 1.        ,
       0.21105528, 0.21105528, 0.21105528, 0.33333333, 0.21105528,
       0.5       , 0.21105528, 0.21105528, 0.21105528, 0.21105528,
       0.21105528, 0.77777778, 0.21105528, 1.        , 0.77777778,
       0.21105528, 0.21105528, 0.21105528, 0.21105528, 0.21105528,
       0.5       , 0.21105528, 0.21105528, 0.        , 0.21105528,
       0.21105528, 0.21105528, 0.21105528, 0.21105528, 0.77777778,
       0.21105528, 0.33333333, 0.21105528, 0.21105528, 0.21105528,
       0.21105528, 0.21105528, 1.        , 0.21105528, 0.77777778,
       1.        , 0.21105528, 0.21105528, 0.21105528, 0.21105528,
       0.21105528, 0.21105528, 0.21105528, 0.21105528, 0.5       ,
       0.21105528, 0.21105528, 0.21105528, 0.75      , 0.21105

In [57]:
from sklearn.metrics import roc_auc_score
y_predict = model_tree.predict(x_test)
rac = roc_auc_score(y_test, y_predict)
rac

0.5635964912280702

Dari kedua algoritma di atas, menurut saya keduanya memiliki selisih yang sedikit terhadap roc auc score maupun validation scorenya. Akan tetapi saya lebih memilih algoritma KNN karena lebih besar roc_auc_score nya dibandingkan dengan decision tree classifier